### PR TITLE
Empty last hash matches allow any kwargs

### PR DESCRIPTION
**Pull request by twalpole**
This fixes issue #374

### CODE REVIEW

**Comment by JonRowe** [comment]
Ok, you'll need a spec for this, also consider not everything responds to `empty?`...

**Comment by twalpole** [comment]
@JonRowe At that point args.last is guaranteed to be a Hash so it is guaranteed to respond to `empty?` and there is a spec already in the commit.

**Comment by twalpole** [comment]
@JonRowe - Just a friendly ping

**Comment by benoittgt** [comment]
Sorry for the late review. This patch looks good to me. Because we do `Hash === args.last` as the first condition we are sure `arg.last.empty?` is done on the proper type. Also @JonRowe I don't understand which test we should add.

For the failing on appveyor. It is unrelated. https://ci.appveyor.com/project/rspec/rspec-support/builds/23996036/job/egb1o129jo145r0t

**Comment by JonRowe** [comment]
Thanks :)

**Pull request merged**
