### PR TITLE
fix rack-cache on < 2.0.0

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by myronmarston** [comment]
What does rack cache have to do with rspec-support?

**Comment by JonRowe** [comment]
> Gem::InstallError: rack-cache requires Ruby version >= 2.0.0.
Using rspec-support 3.4.0.pre from source at /home/travis/build/rspec/rspec-support
An error occurred while installing rack-cache (1.3.0), and Bundler cannot
continue.
Make sure that `gem install rack-cache -v '1.3.0'` succeeds before bundling.

**Comment by JonRowe** [comment]
I think its a dependency of a dependency

**Comment by myronmarston** [comment]
Can you add a comment to the README explaining it's not a direct dependency?  It would be nice to note what it is a dependency of as well.

**Comment by myronmarston** [comment]
Actually, my rspec-support `Gemfile.lock` doesn't have `rack-cache` at all so I really don't think that's needed here.  This might be needed in rspec-rails, though?

**Comment by JonRowe** [comment]
That wouldn't explain mocks failure based on this though?

**Comment by JonRowe** [comment]
Ah no you're right, it's just bundler mangling the output

**Pull request closed without merging**
