### PR TITLE
Add TruffleRuby to CI

### PR DESCRIPTION
**Pull request by bjfish**
I would like to add TruffleRuby to the CI to track compatibility.

### CODE REVIEW

**Comment by pirj** [comment]
That's strange quite strange that Travis doesn't start the build, it may be an indication that there's something wrong with the config file. Most probably related to current Github outage though, as `rspec-core`'s changes are identical and the build was triggered there.

**Comment by bjfish** [comment]
Closing/reopening to see if a Travis build is triggered.

**Comment by benoittgt** [comment]
Build seems to be done but not reported

**Comment by JonRowe** [comment]
See rspec/rspec-core#2712

**Pull request closed without merging**
