### PR TITLE
Updates from rspec-dev (2020-11-21)

### PR DESCRIPTION
**Pull request by JonRowe**
These are some updates, generated from rspec-dev's rake tasks.

### CODE REVIEW

**Comment by pirj** [comment]
> Ripper is supported on 9.1.17.0 according to test suite

👍 Good to know. I indeed to remove one more method from RubyFeatures in `drop-old-rubies`.

**Comment by JonRowe** [comment]
`ripper_supported?` is not a method that should be removed.

**Comment by pirj** [comment]
@JonRowe, do you mind to elaborate why, to support JRuby 9.1?

**Comment by JonRowe** [comment]
Because we need it to flag ripper support on Rubies that don't.

**Comment by pirj** [comment]
Right, Rubinius slipped my mind completely 👍
I had an impression that there's a `jruby?` check when defining `ripper_supported?` in `drop-old-rubies`, but `.rbx?` is the only one.

**Pull request merged**
