### PR TITLE
Support recursive collections in ObjectFormatter

### LINKED ISSUE #267: Stack too deep when displaying failure message
I've constructed a simple reproduction of an issue I noticed. It involves the formatting of an error message, when comparing the equality of a recursive hash.

``` ruby
x = {}
x[:x] = x
puts x #=> {:x=>{...}}
expect(x).to eq({})
```

It gets stuck repeating these calls:
```
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
```

Full stack trace:
```
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:50:in `block in prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `each'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `inject'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:49:in `prepare_hash'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:28:in `prepare_for_inspection'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:8:in `format'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/base_matcher.rb:90:in `actual_formatted'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/eq.rb:11:in `failure_message'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:35:in `handle_failure'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
/Users/blatyo/.rvm/gems/ruby-2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:54:in `to'
```

### PR DESCRIPTION
**Pull request by yujinakayama**
This fixes #267.

### CODE REVIEW

**Comment by yujinakayama** [comment]
I'll rebase this once #269 is merged.

**Comment by JonRowe** [comment]
Ping me when rebased :)

**Comment by yujinakayama** [comment]
ping

**Comment by JonRowe** [comment]
Looks good! Great work.

**Comment by blatyo** [comment]
Cool. Does this handle the case where the recursion is not immediate? For example:

``` ruby
x = {y: {}}
x[:y][:x] = x #=> {:y=>{:x=>{...}}}
```

**Comment by JonRowe** [comment]
It should do

**Pull request merged**
