### PR TITLE
Fix `ReentrantMutex` locking inside `Fiber` spec for ruby-3.2

### PR DESCRIPTION
**Pull request by ojab**
It raises `ThreadError` since https://github.com/ruby/ruby/pull/6680

### CODE REVIEW

**Comment by ojab** [comment]
>First-time contributors need a maintainer to approve running workflows. 

Sending to review, specs are green locally with ruby-3.2-preview3

**Comment by ojab** [comment]
Also, `should reach here` is copypasted from existing spec, shouldn't it be `should not reach here`?

**Comment by pirj** [comment]
The old spec [didn't fail](https://github.com/rspec/rspec-support/actions/runs/3331958379/jobs/5512429885) with `ruby 3.2.0dev (2022-10-26T15:29:12Z master fa0adbad92)`, and it [doesn't fail now](https://github.com/rspec/rspec-support/actions/runs/3502653809/jobs/5867184026) with `ruby 3.2.0dev (2022-11-17T18:58:56Z master 0446d961a0)`.
The [breaking change in Ruby](https://github.com/ruby/ruby/pull/6680) was made between those runs.
We [skip sub-builds for `ruby-head`](https://github.com/rspec/rspec-mocks/actions/runs/3498069669/jobs/5863512421), so it's not possible to confirm the failure from `rspec-mocks` build.

I intend to:
- stash the changes temporarily
- reproduce the failure
- get the changes back

**Comment by pirj** [comment]
A [failing 3.2 build](https://github.com/rspec/rspec-support/actions/runs/3502699953/jobs/5867268699) 👍

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by JonRowe** [comment]
Realistically this should be a pending spec on Ruby 3.2 as its something we should look to fix... (Its not expected to error, it just does)...

**Review by eregon — APPROVED** [review]
Looks good to me, this just adapts the test to the new exception/behavior in CRuby

**Comment by JonRowe** [comment]
I've been working on reworking the spec to run, I don't think its a change in behaviour it's just the way of testing it that changed.

**Comment by eregon** [comment]
It's a behavior change in Ruby, the deadlock is detected and so it doesn't hang.
I think it's difficult to design a test that works with both and is still readable, so I think this is a good solution.

An alternative would be to use a Fiber scheduler, then it would behave as before, since with a scheduler it makes sense to wait. A Fiber scheduler is probably the reason we needed to fix RSpec ReentrantMutex. Would need to make a dummy Fiber scheduler for tests, it's probably fairly short if only used for this example.

**Comment by eregon** [comment]
https://github.com/rspec/rspec-support/issues/501 is the original issue

**Comment by JonRowe** [comment]
I'm closing this for now, we currently skip this on Rubies were its broken, I'd like to fix this spec rather than a no op expect an error (probably needing a fiber scheduler) especially as on my machine its definielty a broken spec (the raise leaks rather than a deadlock)

**Pull request closed without merging**
