### PR TITLE
Differ tests no longer use Differ to report diff expectation

### PR DESCRIPTION
**Pull request by bf4**
For example, previously we would write our differ_spec expectations as

```ruby
 actual = differ.diff(str1, str2)
 expect(actual).to eq(expected)
```

 Which had the suprising (but expected) result
of failure diffing changing the string

```ruby
 actual = differ.diff(str1, str2)
 actual != expected &&
   RSpec::Expectations.fail_with(message, actual, expected)
```

`RSpec::Expectations.fail_with` calls `differ.diff(actual, expected)`
 where differ is 

```plain
**`RSpec::Support::Differ.new**(
   :object_preparer => lambda { |object|
RSpec::Matchers::Composable.surface_descriptions_in(object) },
   :color => RSpec::Matchers.configuration.color?
  )
```

So, all these differ_spec.rb tests where we say `expect(str1).to eq(str2)` will
run through the differ twice on failure.

Rather than test them as `expect(str1 == str2).to eq(true)`, use the `#be_correctly_diffed` matcher.

We're not testing encoding because strings created in differ_spec.rb have a
default encoding of UTF-8 in all cases, but string created in the differ.rb
may be US-ASCII in MRI prior to 2.0 else UTF-8. 
https://github.com/ruby/ruby/blob/aacc35e144/encoding.c#L1741

Refs:
- https://github.com/rspec/rspec-support/pull/167
- https://github.com/rspec/rspec-support/pull/151
- https://github.com/rspec/rspec-support/pull/134#issuecomment-68984440

### CODE REVIEW

**Comment by JonRowe** [comment]
Ok I like this approach so this isn't a block, but I'm wondering if "correctly" diffed is the right name for the matcher, `be_diffed_as(expected)` seems more natural.

**Comment by bf4** [comment]
@JonRowe renamed.  There is duplication with the matcher in encoded_string_spec but I figure that can be a later refactor if desired.

**Comment by JonRowe** [comment]
Thanks, would you like to tackle the duplication?

**Comment by bf4** [comment]
Sure. What do you think about putting it in `lib/rspec/support/spec/string_matcher.rb` and requiring it directly in the two specs?jkl;

**Comment by JonRowe** [comment]
Sure

**Comment by bf4** [comment]
ref #176

**Pull request merged**
