### PR TITLE
Updates from rspec-dev (2022-01-26)

### PR DESCRIPTION
**Pull request by JonRowe**
These are some updates, generated from rspec-dev's rake tasks.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
<Feels good meme.png>
Thanks!

**Comment by pirj** [comment]
Feel free to merge,
```
LoadError:
  cannot load such file -- net/smtp
```
I didn't get to fixing [this](https://github.com/rspec/rspec-rails/blob/main/Gemfile-rails-dependencies#L34) for sub-builds.

**Comment by JonRowe** [comment]
@pirj I'll put back the skip for now, I'm looking for green builds on the core libraries on `main` and `3-10-maintenance` to do some tidy up, patch releases and prep for a 3.11

**Comment by pirj** [comment]
It's fine, I believe https://github.com/rspec/rspec-rails/pull/2568 should fix it for builds with no `RAILS_VERSION` specified like those sub-builds.

**Pull request merged**
