### PR TITLE
Skip encoding spec on windows

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by JonRowe** [comment]
Anyone have any objection to this @rspec/rspec? Just seems to be flakey and I don't have the time to debug windows...

**Comment by soulcutter** [comment]
Seems reasonable to me.

**Comment by bf4** [comment]
@JonRowe can you ping me on EncodedString stuff like this? I'll look into it (at some point :)

**Comment by JonRowe** [comment]
You're welcome to look into the windows failure now if you like ;)

**Pull request merged**
