### PR TITLE
Updates from rspec-dev (2018-04-03)

### PR DESCRIPTION
**Pull request by JonRowe**
These are some updates, generated from rspec-dev's rake tasks.

### CODE REVIEW

**Comment by benoittgt** [comment]
Crash on Travis for Ruby 2.5.1

```
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/dep_proxy (LoadError)
```

People fix this issue with https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916 or https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443

But we already have it https://github.com/rspec/rspec-support/blob/eaa1df8a9f6455830df3ace4350f10008fc9736b/.travis.yml#L11

Could we switch from `gem update --system` to `gem install bundler`?

**Comment by JonRowe** [comment]
This Rails specific, see rspec/rspec-rails#1982

**Comment by benoittgt** [comment]
👏

**Comment by JonRowe** [comment]
Merging based on approval of rspec/rspec-dev#203

**Pull request merged**
